import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const goga = localFont({
  src: [
    {
      path: '../../public/fonts/GogaTest-Extrabold-BF6646d5d7d0a2b.otf',
      
    }
  ],
  variable: '--font-goga',
});

export const metadata: Metadata = {
  title: 'Code Reroute',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${goga.variable} font-sans antialiased`}>
        {children}
      </body>
    </html>
  );
}
